# Site settings
theme: ''
title: "Raul San Martin"
SEOtitle: "Raul San Martin · Student/Developer"
description: "I am a Telecommunication Technologies Engineering student living in Madrid."
url: "https://raulsanmartin.me"
baseurl: ""
lang: en
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.png"
logo: "/assets/images/logo.png"
author: "Raúl San Martín Aniceto"
permalink: /:categories/:title/

# Top bar
topbar: "<b>Raul San Martin Aniceto</b> / MrAnnix"

# Liquid
liquid:
  error_mode: strict

# Markdown
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Paginate blog
paginate: 10
paginate_path: "/blog/page:num"

# Categories and tags pages
tag_page: '/tags/'
category_page: '/categories/'

# Addons
google-site-verification: "4KpPIPbUzRNI1DJR-OrOS5tNYrNvTIMj2Xh9bIybdPE"

# Social settings (you can use Font Awesome icons [fa fa-icon] or Iconmonstr ones [im im-icon])
email: hello@[this domain]

social:
  - title: e-mail
    description: "hello@[this domain] for e-mail"
    link: "/contact"
  - title: github
    description: "MrAnnix on GitHub"
    link: "https://github.com/MrAnnix"
  - title: linkedin
    description: "Raul San Martin on Linkedin"
    link: "https://www.linkedin.com/in/raul-san-martin-aniceto"
  - title: twitter
