# Site settings
title: Raul San Martin Aniceto
SEOTitle: Raul San Martin · Student/Developer
description: I am a Telecommunication Technologies Engineering student living in Madrid.
url: "https://raulsanmartin.me"
baseurl: ""
language: en
favicon: "/assets/images/favicon.png"
author: "Raúl San Martín Aniceto"
permalink: /:categories/:title/

# Markdown
markdown: kramdown
mathjax: true

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Paginate blog
paginate: 10
paginate_path: "/blog/page:num"

# Categories and tags pages
tag_page: '/tags/'
category_page: '/categories/'

# Addons
google-site-verification: "4KpPIPbUzRNI1DJR-OrOS5tNYrNvTIMj2Xh9bIybdPE"

# Social settings (you can use Font Awesome icons [fa fa-icon] or Iconmonstr ones [im im-icon])
social:
  - title: Github
    icon: "im im-github"
    link: "https://github.com/MrAnnix"
  - title: Twitter
    icon: "im im-twitter"
    link: "https://twitter.com/MrAnnix"
  - title: Linkedin
    icon: "im im-linkedin"
    link: "https://www.linkedin.com/in/raul-san-martin-aniceto"
  - title: Email
    icon: "im im-mail"
    smoothscroll: yes
    link: "/#contact"
